on:
    workflow_dispatch:
    push:
      branches: main
  
name: Quarto Publish

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Render and Publish
              run: |
                quarto render
        
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs
                cname: www.learnml.io