project:
  type: website

website:
  title: "learnml.io"
  site-url: https://www.learnml.io
  repo-url: "https://github.com/mrdbourke/learn-ml"
  repo-actions: [edit, issue]
  description: a blog about learning machine learning
  twitter-card: true 
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    clean-url: true
    code-tools:
      source: repo



