project:
  type: website

website:
  title: "learn ml"
  site-url: "https://www.learnml.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



