---
title: "Learning ML - Timeline"
---

## 2025-05-31

Started collecting high-performing Apache 2.0 (or MIT) licensed object detection models in a post.

These models perform on par or better than YOLO equivalents except have a more permissive license to use, even commercially.

The collection [here](https://www.learnml.io/posts/apache-object-detection-models/).

## 2025-04-17

Continuing on from the previous bounding box formats post, another object detection themed post with a [hands-on guide for IoU](https://www.learnml.io/posts/a-gentle-guide-to-intersection-over-union/) (Intersection over Union).

IoU measures how much two bounding boxes overlap.

It's commonly used to evaluate an object detection model's predictions in comparison to the ground truth labels.

Wherever you see the term "mAP" (Mean Average Precision, commonly seen reported for object detection models/papers), chances are, IoU is being used.

More on mAP soon.

## 2025-02-06

First blog post for 2025.

A [guide to different bounding box formats](https://www.learnml.io/posts/a-guide-to-bounding-box-formats/).

I've been diving into object detection (stay tuned for a future tutorial) and found that different bounding box formats can be an absolute nightmare to deal with.

You'll have a well-trained model but your boxes will look terrible because they're in the wrong format (this is mostly my own fault for not being careful which format to use).

Either way, I wanted a resource to go through the major bounding box formats and some examples of when to use them.

I'd like this to be a trend going forward, learn something by experimenting and creating a working example then compound the knowledge by writing about how to it/evaluate it yourself.

--

On another note, January 2025 was one of the best months for open-source AI in recent memory. More on that soon.

## 2024-08-18

Another [blog post](https://www.learnml.io/posts/the-importance-of-a-test-set/) is live!

This importance of a test set.

This is fun.

Will eventually sort out the rest of the pages on this website.

E.g about, this homepage, tutorials and more.

Slowly but surely.

## 2024-08-10

More coming soon. 

Just getting this bad boy up and running as a lil weekend project so I can start to write down ideas whenever they come into my head.

See the [start blog post](https://www.learnml.io/posts/2024-08-10-start-ml-blog/) for more.
